development:
  telegram:
    # Single bot can be specified like this
    # bot: 
    # or
    bot:
      token: 7096035631:AAE6EpahCA6GDWo_BSTJasMxmswa5KQRpq0
      username: SomeBot
      # server: http://local.bot.api.server